#ifndef ALGINE_CONSTANTS
#define ALGINE_CONSTANTS

#define ALGINE_NORMAL_MAPPING_MODE_ENABLED 0x000
#define ALGINE_NORMAL_MAPPING_MODE_DUAL 0x001
#define ALGINE_NORMAL_MAPPING_MODE_DISABLED 0x002

#define ALGINE_SHADOW_MAPPING_MODE_ENABLED 0x100
#define ALGINE_SHADOW_MAPPING_MODE_SIMPLE 0x101
#define ALGINE_SHADOW_MAPPING_MODE_DISABLED 0x102
#define ALGINE_SHADOW_MAPPING_TYPE_POINT_LIGHTING 0x103
#define ALGINE_SHADOW_MAPPING_TYPE_DIR_LIGHTING 0x104

#define ALGINE_BLOOM_MODE_ENABLED 0x200
#define ALGINE_BLOOM_MODE_DISABLED 0x201
#define ALGINE_BLOOM_TYPE_ADD 0x202
#define ALGINE_BLOOM_TYPE_SCREEN 0x203

#define ALGINE_DOF_MODE_ENABLED 0x300
#define ALGINE_CINEMATIC_DOF_MODE_ENABLED 0x301
#define ALGINE_DOF_MODE_DISABLED 0x302

#define ALGINE_TEXTURE_MAPPING_MODE_ENABLED 0x400
#define ALGINE_TEXTURE_MAPPING_MODE_DUAL 0x401
#define ALGINE_TEXTURE_MAPPING_MODE_DISABLED 0x402

#define ALGINE_LIGHTING_MODE_ENABLED 0x500
#define ALGINE_LIGHTING_MODE_DISABLED 0x501

#define ALGINE_ATTENUATION_MODE_ENABLED 0x600
#define ALGINE_ATTENUATION_MODE_DISABLED 0x601

#define ALGINE_SSR_MODE_ENABLED 0x700
#define ALGINE_SSR_MODE_DISABLED 0x701

#define ALGINE_BONE_SYSTEM_ENABLED 0x800
#define ALGINE_BONE_SYSTEM_DISABLED 0x801

#define ALGINE_MATERIAL_NAME "name"
#define ALGINE_MATERIAL_AMBIENT_TEX "ambientTex"
#define ALGINE_MATERIAL_DIFFUSE_TEX "diffuseTex"
#define ALGINE_MATERIAL_SPECULAR_TEX "specularTex"
#define ALGINE_MATERIAL_NORMAL_TEX "normalTex"
#define ALGINE_MATERIAL_REFLECTION_TEX "reflectionTex"
#define ALGINE_MATERIAL_JITTER_TEX "jitterTex"
#define ALGINE_MATERIAL_REFLECTION "reflection"
#define ALGINE_MATERIAL_JITTER "jitter"
#define ALGINE_MATERIAL_AMBIENT_STRENGTH "ambientStrength"
#define ALGINE_MATERIAL_DIFFUSE_STRENGTH "diffuseStrength"
#define ALGINE_MATERIAL_SPECULAR_STRENGTH "specularStrength"
#define ALGINE_MATERIAL_SHININESS "shininess"

#define ALGINE_DEPTH_COMPONENT GL_DEPTH_COMPONENT
#define ALGINE_DEPTH_ATTACHMENT GL_DEPTH_ATTACHMENT

#endif /* ALGINE_CONSTANTS */