/**
 * unsconstants - undef shader constants
 * 
 * Generated from sconstants.h using vscode replacement:
 *     replaceAll(' ".*"', ''), replaceAll('define', 'undef')
 */

// CS vertex shader names
#undef ALGINE_NAME_CS_MAT_MODEL
#undef ALGINE_NAME_CS_MAT_VIEW
#undef ALGINE_NAME_CS_MAT_PVM
#undef ALGINE_NAME_CS_MAT_VM
#undef ALGINE_NAME_CS_BONES
#undef ALGINE_NAME_CS_SWITCH_NORMAL_MAPPING
#undef ALGINE_NAME_CS_BONE_ATTRIBS_PER_VERTEX
#undef ALGINE_NAME_CS_IN_POSITION
#undef ALGINE_NAME_CS_IN_NORMAL
#undef ALGINE_NAME_CS_IN_TANGENT
#undef ALGINE_NAME_CS_IN_BITANGENT
#undef ALGINE_NAME_CS_IN_TEXCOORD
#undef ALGINE_NAME_CS_IN_BONE_IDS
#undef ALGINE_NAME_CS_IN_BONE_WEIGHTS
    
// CS fragment shader names
#undef ALGINE_NAME_CS_VIEW_POSITION
#undef ALGINE_NAME_CS_POINT_LIGHTS_COUNT
#undef ALGINE_NAME_CS_DIR_LIGHTS_COUNT
#undef ALGINE_NAME_CS_SHADOW_DISKRADIUS_K
#undef ALGINE_NAME_CS_SHADOW_DISKRADIUS_MIN
#undef ALGINE_NAME_CS_SHADOW_OPACITY
#undef ALGINE_NAME_CS_MATERIAL_AMBIENT_TEX
#undef ALGINE_NAME_CS_MATERIAL_DIFFUSE_TEX
#undef ALGINE_NAME_CS_MATERIAL_SPECULAR_TEX
#undef ALGINE_NAME_CS_MATERIAL_NORMAL_TEX
#undef ALGINE_NAME_CS_MATERIAL_REFLECTIONSTRENGTH_TEX
#undef ALGINE_NAME_CS_MATERIAL_JITTER_TEX
#undef ALGINE_NAME_CS_MATERIAL_AMBIENT_COLOR
#undef ALGINE_NAME_CS_MATERIAL_DIFFUSE_COLOR
#undef ALGINE_NAME_CS_MATERIAL_SPECULAR_COLOR
#undef ALGINE_NAME_CS_MATERIAL_AMBIENT_STRENGTH
#undef ALGINE_NAME_CS_MATERIAL_DIFFUSE_STRENGTH
#undef ALGINE_NAME_CS_MATERIAL_SPECULAR_STRENGTH
#undef ALGINE_NAME_CS_MATERIAL_SHININESS
#undef ALGINE_NAME_CS_SWITCH_TEXTURE_MAPPING
#undef ALGINE_NAME_CS_POINT_LIGHTS
#undef ALGINE_NAME_CS_DIR_LIGHTS

// SS vertex shader
#undef ALGINE_NAME_SS_IN_POSITION
#undef ALGINE_NAME_SS_IN_BONE_IDS
#undef ALGINE_NAME_SS_IN_BONE_WEIGHTS
#undef ALGINE_NAME_SS_MAT_LIGHT_SPACE
#undef ALGINE_NAME_SS_MAT_MODEL
#undef ALGINE_NAME_SS_BONES
#undef ALGINE_NAME_SS_BONE_ATTRIBS_PER_VERTEX
    
// SS geometry shader
#undef ALGINE_NAME_SS_MAT_SHADOW

// SS fragment shader
#undef ALGINE_NAME_SS_LAMP_POSITION
#undef ALGINE_NAME_SS_FAR_PLANE

// SSRS vertex shader
#undef ALGINE_NAME_SSRS_IN_POSITION
#undef ALGINE_NAME_SSRS_IN_TEXCOORD

// SSRS fragment shader
#undef ALGINE_NAME_SSRS_SAMPLER_MAP_COLOR
#undef ALGINE_NAME_SSRS_SAMPLER_MAP_NORMAL
#undef ALGINE_NAME_SSRS_SAMPLER_MAP_SSRVALUES
#undef ALGINE_NAME_SSRS_SAMPLER_MAP_POSITION
#undef ALGINE_NAME_SSRS_MAT_PROJECTION
#undef ALGINE_NAME_SSRS_MAT_VIEW
// SSR - Screen Space Reflections
#undef ALGINE_NAME_SSRS_SKYCOLOR
#undef ALGINE_NAME_SSRS_BINARYSEARCHCOUNT
#undef ALGINE_NAME_SSRS_RAYMARCHCOUNT
#undef ALGINE_NAME_SSRS_STEP
#undef ALGINE_NAME_SSRS_LLIMITER
#undef ALGINE_NAME_SSRS_MINRAYSTEP

// dof blur vertex shader
#undef ALGINE_NAME_DOFBLUR_IN_POSITION
#undef ALGINE_NAME_DOFBLUR_IN_TEXCOORD
    
// dof blur fragment shader
#undef ALGINE_NAME_DOFBLUR_SAMPLER_IMAGE
#undef ALGINE_NAME_DOFBLUR_SAMPLER_MAP_POSITION
#undef ALGINE_NAME_DOFBLUR_SIGMA_MIN
#undef ALGINE_NAME_DOFBLUR_SIGMA_MAX
#undef ALGINE_NAME_DOFBLUR_FOCAL_DEPTH
#undef ALGINE_NAME_DOFBLUR_FOCAL_RANGE
#undef ALGINE_NAME_DOFBLUR_CINEMATIC_DOF_PLANE_IN_FOCUS
#undef ALGINE_NAME_DOFBLUR_CINEMATIC_DOF_APERTURE
#undef ALGINE_NAME_DOFBLUR_CINEMATIC_DOF_IMAGE_DISTANCE

// blend vertex shader
#undef ALGINE_NAME_BLEND_IN_POSITION
#undef ALGINE_NAME_BLEND_IN_TEXCOORD

// blend fragment shader
#undef ALGINE_NAME_BLEND_SAMPLER_BLOOM
#undef ALGINE_NAME_BLEND_SAMPLER_IMAGE
#undef ALGINE_NAME_BLEND_EXPOSURE
#undef ALGINE_NAME_BLEND_GAMMA

// bloom search vertex
#undef ALGINE_NAME_BLOOM_SEARCH_IN_POSITION
#undef ALGINE_NAME_BLOOM_SEARCH_IN_TEXCOORD

// bloom search fragment
#undef ALGINE_NAME_BLOOM_SEARCH_THRESHOLD
#undef ALGINE_NAME_BLOOM_SEARCH_BRIGHTNESS_THRESHOLD
#undef ALGINE_NAME_BLOOM_SEARCH_IMAGE

// blur vertex
#undef ALGINE_NAME_BLUR_IN_POSITION
#undef ALGINE_NAME_BLUR_IN_TEXCOORD

// blur fragment
#undef ALGINE_NAME_BLUR_IMAGE
#undef ALGINE_NAME_BLUR_KERNEL

// cubemap vertex
#undef ALGINE_NAME_CUBEMAP_IN_POSITION
#undef ALGINE_NAME_CUBEMAP_MAT_TRANSFORM

// cubemap fragment
#undef ALGINE_NAME_CUBEMAP_CUBEMAP
#undef ALGINE_NAME_CUBEMAP_COLOR
#undef ALGINE_NAME_CUBEMAP_POS_SCALING

// lamp.cpp shader constants
#undef ALGINE_NAME_CS_LIGHT_POS
#undef ALGINE_NAME_CS_LIGHT_COLOR
#undef ALGINE_NAME_CS_LIGHT_KC
#undef ALGINE_NAME_CS_LIGHT_KL
#undef ALGINE_NAME_CS_LIGHT_KQ
#undef ALGINE_NAME_CS_LIGHT_FAR
#undef ALGINE_NAME_CS_LIGHT_BIAS
#undef ALGINE_NAME_CS_LIGHT_MAX_BIAS
#undef ALGINE_NAME_CS_LIGHT_MIN_BIAS
#undef ALGINE_NAME_CS_LIGHT_SHADOW_MAP
#undef ALGINE_NAME_CS_LIGHT_MATRIX