#ifndef ALGINE_CONSTANTS
#define ALGINE_CONSTANTS

#define ALGINE_NORMAL_MAPPING_MODE_ENABLED 0
#define ALGINE_NORMAL_MAPPING_MODE_DUAL 1
#define ALGINE_NORMAL_MAPPING_MODE_DISABLED 2

#define ALGINE_SHADOW_MAPPING_MODE_ENABLED 3
#define ALGINE_SHADOW_MAPPING_MODE_SIMPLE 4
#define ALGINE_SHADOW_MAPPING_MODE_DISABLED 5

#define ALGINE_BLOOM_MODE_ENABLED 6
#define ALGINE_BLOOM_MODE_DISABLED 7

#define ALGINE_DOF_MODE_ENABLED 8
#define ALGINE_DOF_MODE_DISABLED 9

#define ALGINE_TEXTURE_MAPPING_MODE_ENABLED 10
#define ALGINE_TEXTURE_MAPPING_MODE_DUAL 11
#define ALGINE_TEXTURE_MAPPING_MODE_DISABLED 12

#define ALGINE_LIGHTING_MODE_ENABLED 13
#define ALGINE_LIGHTING_MODE_DISABLED 14

#define ALGINE_ATTENUATION_MODE_ENABLED 15
#define ALGINE_ATTENUATION_MODE_DISABLED 16

#define ALGINE_SSR_MODE_ENABLED 17
#define ALGINE_SSR_MODE_DISABLED 18

#endif /* ALGINE_CONSTANTS */