#ifndef ALGINE_CONSTANTS
#define ALGINE_CONSTANTS

#define ALGINE_NORMAL_MAPPING_MODE_ENABLED 0
#define ALGINE_NORMAL_MAPPING_MODE_DUAL 1
#define ALGINE_NORMAL_MAPPING_MODE_DISABLED 2

#define ALGINE_SHADOW_MAPPING_MODE_ENABLED 3
#define ALGINE_SHADOW_MAPPING_MODE_SIMPLE 4
#define ALGINE_SHADOW_MAPPING_MODE_DISABLED 5

#define ALGINE_BLOOM_MODE_ENABLED 6
#define ALGINE_BLOOM_MODE_DISABLED 7

#define ALGINE_DOF_MODE_ENABLED 8
#define ALGINE_CINEMATIC_DOF_MODE_ENABLED 9
#define ALGINE_DOF_MODE_DISABLED 10

#define ALGINE_TEXTURE_MAPPING_MODE_ENABLED 11
#define ALGINE_TEXTURE_MAPPING_MODE_DUAL 12
#define ALGINE_TEXTURE_MAPPING_MODE_DISABLED 13

#define ALGINE_LIGHTING_MODE_ENABLED 14
#define ALGINE_LIGHTING_MODE_DISABLED 15

#define ALGINE_ATTENUATION_MODE_ENABLED 16
#define ALGINE_ATTENUATION_MODE_DISABLED 17

#define ALGINE_SSR_MODE_ENABLED 18
#define ALGINE_SSR_MODE_DISABLED 19

#define ALGINE_MATERIAL_NAME "name"
#define ALGINE_MATERIAL_AMBIENT_TEX "ambientTex"
#define ALGINE_MATERIAL_DIFFUSE_TEX "diffuseTex"
#define ALGINE_MATERIAL_SPECULAR_TEX "specularTex"
#define ALGINE_MATERIAL_NORMAL_TEX "normalTex"
#define ALGINE_MATERIAL_REFLECTION_TEX "reflectionTex"
#define ALGINE_MATERIAL_JITTER_TEX "jitterTex"
#define ALGINE_MATERIAL_REFLECTION "reflection"
#define ALGINE_MATERIAL_JITTER "jitter"
#define ALGINE_MATERIAL_AMBIENT_STRENGTH "ambientStrength"
#define ALGINE_MATERIAL_DIFFUSE_STRENGTH "diffuseStrength"
#define ALGINE_MATERIAL_SPECULAR_STRENGTH "specularStrength"
#define ALGINE_MATERIAL_SHININESS "shininess"

#endif /* ALGINE_CONSTANTS */