/**
 * unsconstants - undef shader constants
 */

// CS vertex shader names
#undef ALGINE_NAME_CS_MAT_MODEL
#undef ALGINE_NAME_CS_MAT_VIEW
#undef ALGINE_NAME_CS_MAT_PVM
#undef ALGINE_NAME_CS_MAT_VM
#undef ALGINE_NAME_CS_SWITCH_NORMAL_MAPPING
#undef ALGINE_NAME_CS_IN_POSITION
#undef ALGINE_NAME_CS_IN_NORMAL
#undef ALGINE_NAME_CS_IN_TANGENT
#undef ALGINE_NAME_CS_IN_BITANGENT
#undef ALGINE_NAME_CS_IN_TEXCOORD
    
// CS fragment shader names
#undef ALGINE_NAME_CS_VIEW_POSITION
#undef ALGINE_NAME_CS_LAMPS_COUNT
#undef ALGINE_NAME_CS_BRIGHTNESS_THRESHOLD
#undef ALGINE_NAME_CS_SHADOW_FAR_PLANE
#undef ALGINE_NAME_CS_SHADOW_DISKRADIUS_K
#undef ALGINE_NAME_CS_SHADOW_DISKRADIUS_MIN
#undef ALGINE_NAME_CS_SHADOW_BIAS
#undef ALGINE_NAME_CS_FOCAL_DEPTH
#undef ALGINE_NAME_CS_FOCAL_RANGE
#undef ALGINE_NAME_CS_SHADOW_MAPS
#undef ALGINE_NAME_CS_SAMPLER_MAPPING_AMBIENT
#undef ALGINE_NAME_CS_SAMPLER_MAPPING_DIFFUSE
#undef ALGINE_NAME_CS_SAMPLER_MAPPING_SPECULAR
#undef ALGINE_NAME_CS_SAMPLER_MAPPING_NORMAL
#undef ALGINE_NAME_CS_COLOR_MAPPING_AMBIENT
#undef ALGINE_NAME_CS_COLOR_MAPPING_DIFFUSE
#undef ALGINE_NAME_CS_COLOR_MAPPING_SPECULAR
#undef ALGINE_NAME_CS_SWITCH_TEXTURE_MAPPING
#undef ALGINE_NAME_CS_LAMPS

// SS vertex shader
#undef ALGINE_NAME_SS_MAT_MODEL
#undef ALGINE_NAME_SS_IN_POSITION
    
// SS geometry shader
#undef ALGINE_NAME_SS_MAT_SHADOW

// SS fragment shader
#undef ALGINE_NAME_SS_LAMP_POSITION
#undef ALGINE_NAME_SS_FAR_PLANE

// BLUS vertex shader
#undef ALGINE_NAME_BLUS_IN_POSITION
#undef ALGINE_NAME_BLUS_IN_TEXCOORD
    
// BLUS fragment shader
#undef ALGINE_NAME_BLUS_SAMPLER_BLOOM
#undef ALGINE_NAME_BLUS_SAMPLER_DOF
#undef ALGINE_NAME_BLUS_SIGMA_MIN
#undef ALGINE_NAME_BLUS_SIGMA_MAX
#undef ALGINE_NAME_BLUS_KERNEL_BLOOM

// BLES vertex shader
#undef ALGINE_NAME_BLES_IN_POSITION
#undef ALGINE_NAME_BLES_IN_TEXCOORD

// BLES fragment shader
#undef ALGINE_NAME_BLES_SAMPLER_BLOOM_SCENE
#undef ALGINE_NAME_BLES_SAMPLER_DOF_SCENE
#undef ALGINE_NAME_BLES_EXPOSURE
#undef ALGINE_NAME_BLES_GAMMA

// lamp.cpp shader constants
#undef ALGINE_NAME_CS_LAMP_AMBIENT_STRENGTH
#undef ALGINE_NAME_CS_LAMP_DIFFUSE_STRENGTH
#undef ALGINE_NAME_CS_LAMP_SPECULAR_STRENGTH
#undef ALGINE_NAME_CS_LAMP_SHININESS
#undef ALGINE_NAME_CS_LAMP_LAMP_POS
#undef ALGINE_NAME_CS_LAMP_LAMP_COLOR
#undef ALGINE_NAME_CS_LAMP_KC
#undef ALGINE_NAME_CS_LAMP_KL
#undef ALGINE_NAME_CS_LAMP_KQ