/**
 * unsconstants - undef shader constants
 */

// CS vertex shader names
#undef ALGINE_NAME_CS_MAT_MODEL
#undef ALGINE_NAME_CS_MAT_VIEW
#undef ALGINE_NAME_CS_MAT_PVM
#undef ALGINE_NAME_CS_MAT_VM
#undef ALGINE_NAME_CS_BONES
#undef ALGINE_NAME_CS_SWITCH_NORMAL_MAPPING
#undef ALGINE_NAME_CS_BONE_ATTRIBS_PER_VERTEX
#undef ALGINE_NAME_CS_IN_POSITION
#undef ALGINE_NAME_CS_IN_NORMAL
#undef ALGINE_NAME_CS_IN_TANGENT
#undef ALGINE_NAME_CS_IN_BITANGENT
#undef ALGINE_NAME_CS_IN_TEXCOORD
#undef ALGINE_NAME_CS_IN_BONE_IDS
#undef ALGINE_NAME_CS_IN_BONE_WEIGHTS
    
// CS fragment shader names
#undef ALGINE_NAME_CS_VIEW_POSITION
#undef ALGINE_NAME_CS_LAMPS_COUNT
#undef ALGINE_NAME_CS_SHADOW_DISKRADIUS_K
#undef ALGINE_NAME_CS_SHADOW_DISKRADIUS_MIN
#undef ALGINE_NAME_CS_SHADOW_BIAS
#undef ALGINE_NAME_CS_SHADOW_OPACITY
#undef ALGINE_NAME_CS_FOCAL_DEPTH
#undef ALGINE_NAME_CS_FOCAL_RANGE
#undef ALGINE_NAME_CS_SHADOW_MAPS
#undef ALGINE_NAME_CS_MATERIAL_AMBIENT_TEX
#undef ALGINE_NAME_CS_MATERIAL_DIFFUSE_TEX
#undef ALGINE_NAME_CS_MATERIAL_SPECULAR_TEX
#undef ALGINE_NAME_CS_MATERIAL_NORMAL_TEX
#undef ALGINE_NAME_CS_MATERIAL_REFLECTIONSTRENGTH_TEX
#undef ALGINE_NAME_CS_MATERIAL_JITTER_TEX
#undef ALGINE_NAME_CS_MATERIAL_AMBIENT_COLOR
#undef ALGINE_NAME_CS_MATERIAL_DIFFUSE_COLOR
#undef ALGINE_NAME_CS_MATERIAL_SPECULAR_COLOR
#undef ALGINE_NAME_CS_MATERIAL_AMBIENT_STRENGTH
#undef ALGINE_NAME_CS_MATERIAL_DIFFUSE_STRENGTH
#undef ALGINE_NAME_CS_MATERIAL_SPECULAR_STRENGTH
#undef ALGINE_NAME_CS_MATERIAL_SHININESS
#undef ALGINE_NAME_CS_SWITCH_TEXTURE_MAPPING
#undef ALGINE_NAME_CS_LAMPS
#undef ALGINE_NAME_CS_CINEMATIC_DOF_PLANE_IN_FOCUS
#undef ALGINE_NAME_CS_CINEMATIC_DOF_APERTURE
#undef ALGINE_NAME_CS_CINEMATIC_DOF_IMAGE_DISTANCE

// SS vertex shader
#undef ALGINE_NAME_SS_IN_POSITION
#undef ALGINE_NAME_SS_IN_BONE_IDS
#undef ALGINE_NAME_SS_IN_BONE_WEIGHTS
#undef ALGINE_NAME_SS_MAT_MODEL
#undef ALGINE_NAME_SS_BONES
#undef ALGINE_NAME_SS_BONE_ATTRIBS_PER_VERTEX
    
// SS geometry shader
#undef ALGINE_NAME_SS_MAT_SHADOW

// SS fragment shader
#undef ALGINE_NAME_SS_LAMP_POSITION
#undef ALGINE_NAME_SS_FAR_PLANE

// SSS vertex shader
#undef ALGINE_NAME_SSS_IN_POSITION
#undef ALGINE_NAME_SSS_IN_TEXCOORD

// SSS fragment shader
#undef ALGINE_NAME_SSS_SAMPLER_MAP_COLOR
#undef ALGINE_NAME_SSS_SAMPLER_MAP_NORMAL
#undef ALGINE_NAME_SSS_SAMPLER_MAP_SSRVALUES
#undef ALGINE_NAME_SSS_SAMPLER_MAP_POSITION
#undef ALGINE_NAME_SSS_MAT_PROJECTION
#undef ALGINE_NAME_SSS_MAT_VIEW
// SSR - Screen Space Reflections
#undef ALGINE_NAME_SSS_SSR_SKYCOLOR
#undef ALGINE_NAME_SSS_SSR_BINARYSEARCHCOUNT
#undef ALGINE_NAME_SSS_SSR_RAYMARCHCOUNT
#undef ALGINE_NAME_SSS_SSR_STEP
#undef ALGINE_NAME_SSS_SSR_LLIMITER
#undef ALGINE_NAME_SSS_SSR_MINRAYSTEP
// BL - bloom
#undef ALGINE_NAME_SSS_BL_VECTHRESHOLD
#undef ALGINE_NAME_SSS_BL_BRIGHTNESSTHRESHOLD

// BLUS vertex shader
#undef ALGINE_NAME_BLUS_IN_POSITION
#undef ALGINE_NAME_BLUS_IN_TEXCOORD
    
// BLUS fragment shader
#undef ALGINE_NAME_BLUS_SAMPLER_BLOOM
#undef ALGINE_NAME_BLUS_SAMPLER_SCENE
#undef ALGINE_NAME_BLUS_SAMPLER_DOF_BUFFER
#undef ALGINE_NAME_BLUS_SIGMA_MIN
#undef ALGINE_NAME_BLUS_SIGMA_MAX
#undef ALGINE_NAME_BLUS_KERNEL_BLOOM

// BLES vertex shader
#undef ALGINE_NAME_BLES_IN_POSITION
#undef ALGINE_NAME_BLES_IN_TEXCOORD

// BLES fragment shader
#undef ALGINE_NAME_BLES_SAMPLER_BLOOM_SCENE
#undef ALGINE_NAME_BLES_SAMPLER_DOF_SCENE
#undef ALGINE_NAME_BLES_EXPOSURE
#undef ALGINE_NAME_BLES_GAMMA

// lamp.cpp shader constants
#undef ALGINE_NAME_CS_LAMP_LAMP_POS
#undef ALGINE_NAME_CS_LAMP_LAMP_COLOR
#undef ALGINE_NAME_CS_LAMP_KC
#undef ALGINE_NAME_CS_LAMP_KL
#undef ALGINE_NAME_CS_LAMP_KQ
#undef ALGINE_NAME_CS_LAMP_FAR