#ifndef ALGINE_MOUSEKEYCONVERTER_H
#define ALGINE_MOUSEKEYCONVERTER_H

#include <algine/core/input/MouseKey.h>

#include <GLFW/glfw3.h>

/*
 * Macros have been generated by MouseKeyConverterGen.py
 * Do not edit!
 */

namespace algine {
#define glfwToInternal(key, glfwKey) if (value == glfwKey) return MouseKey::key

inline MouseKey getMouseKey(uint value) {
    glfwToInternal(Key1, GLFW_MOUSE_BUTTON_1);
    glfwToInternal(Key2, GLFW_MOUSE_BUTTON_2);
    glfwToInternal(Key3, GLFW_MOUSE_BUTTON_3);
    glfwToInternal(Key4, GLFW_MOUSE_BUTTON_4);
    glfwToInternal(Key5, GLFW_MOUSE_BUTTON_5);
    glfwToInternal(Key6, GLFW_MOUSE_BUTTON_6);
    glfwToInternal(Key7, GLFW_MOUSE_BUTTON_7);
    glfwToInternal(Key8, GLFW_MOUSE_BUTTON_8);

    return MouseKey::Unknown;
}

#undef glfwToInternal

#define internalToGlfw(key, glfwValue) if (value == MouseKey::key) return glfwValue

inline uint getGLFWMouseKeyValue(MouseKey value) {
    internalToGlfw(Key1, GLFW_MOUSE_BUTTON_1);
    internalToGlfw(Key2, GLFW_MOUSE_BUTTON_2);
    internalToGlfw(Key3, GLFW_MOUSE_BUTTON_3);
    internalToGlfw(Key4, GLFW_MOUSE_BUTTON_4);
    internalToGlfw(Key5, GLFW_MOUSE_BUTTON_5);
    internalToGlfw(Key6, GLFW_MOUSE_BUTTON_6);
    internalToGlfw(Key7, GLFW_MOUSE_BUTTON_7);
    internalToGlfw(Key8, GLFW_MOUSE_BUTTON_8);

    return GLFW_KEY_UNKNOWN;
}

#undef internalToGlfw
}

#endif //ALGINE_MOUSEKEYCONVERTER_H
